name: ci

on:
  pull_request:
  push:
    branches: [main]
    tags: ['*']

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: { node-version: 16 }
      - run: npm ci
      - run: npx eslint .

  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: { node-version: 16 }
      - run: npm ci
      - run: npm pack

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: { node-version: 16 }
      - run: npm ci
      - run: npx prettier --check .

  remark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: { node-version: 16 }
      - run: npm ci
      - run: npx remark --frail .

  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: { node-version: 16 }
      - run: npm ci
      - run: npx tsc
